name: 'user-srv'
host: '127.0.0.1'
port: 50051

mysql:
     host: '127.0.0.1'
     port: 3306
     password: 'root'
     name: 'hcshop_user_srv'
     user: 'root'

consul:
      host: '127.0.0.1'
      port: 8500